### ISSUE TITLE
m1l2a - Bulletproof fence at spotlights

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#29]
m1l2a (The Rescue Mission) bulletproof fence at spotlights still a thing ?
Needs to be tested if that is still a issue or if the spotlight operators can now be killed from down there

**Comment by ChannelDaniila** [comment]
Chris, change label from "verify" to "buy". (Fence is actually bulletproof).

**Comment by 1337Smithy** [comment]
I couldn't replicate this on a listen server. I could shoot through fine.

**Comment by 1337Smithy** [comment]
This needs investigation. Are people using different client texture changes? I don't seem to have this problem on my local machine.

**Comment by 1337Smithy** [comment]
Made this into one issue.
