### ISSUE TITLE
m1l2a - Agent (Grillo) Script-AI Follow/Lead player

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#30]
m1l2a - The Agent NPC leading the player/following sometimes does is a bit difficult and can get stuck if players are to far away or to far ahead.
Consequently the Agent will often not help you free the other prisoner upstairs. As a result the blockade that has been added for the coop mod to prevent script getting stuck will not remove it self (Agent needs to be in range).
This makes it impossible for the player to rescue the other prisoner.

**Comment by 1337Smithy** [comment]
Made some improvements, and added hints for the prisoner rescue. I believe before players were hitting choice 2 trigger (not saving the prisoner) before being able to hit choice 1 (saving the prisoner). I've now made those triggers only react properly to the player doing the leading. It prints appropriate hints to the players.

**Comment by ChannelDaniila** [comment]
Not working.

**Comment by ChannelDaniila** [comment]
Oh, this fix is working if spotlights not destroyed.

**Comment by ChannelDaniila** [comment]
Tested, fix is working.
