### ISSUE TITLE
e1l2 - Player can't grab/shoot from Bohler (Cannone da 47/32)

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#32]
(This is old bug, but i remember about it only now)

**Comment by 1337Smithy** [comment]
There are a lot of dev printouts still in e1l2 so dunno how much still needs fixing or finishing tbh. The whole map probably needs a review.

**Comment by 1337Smithy** [comment]
On more inspection, there are flaws with the code for artillery. I'll probably copy/paste what I've done on e2l1 (which isn't flawless either). Will need a bit of time to improve.

**Comment by 1337Smithy** [comment]
All cannons in this map now uses new (but similar) code. Fix: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/8c138d6779dbf45fff42929d25818be716a870b9

**Comment by ChannelDaniila** [comment]
I tested this fix and this works fine.
