### ISSUE TITLE
e1l1 - Only 1 player sit in jeep at cutscene

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#34]
After player 1 enters the battle and the cut-scene starts, other players do not see the cut-scene, but instead of the jeep, they remain in the place where the player should get out of the jeep.
It is hard to explain, but i tryed)

**Comment by Chrissstrahl** [comment]
This sounds like there is a problem with the glue script.
It was changed for better performance a while ago, but I think this might be very well a side effect of that change.

**Comment by 1337Smithy** [comment]
It's to do with cameras. It uses a camera system like e2l1, and it probably never worked, as it's currently coded to set all present players to the jeep camera and does nothing for new players connecting after this point. 

I'll copy/paste the system I implemented for e2l1 and change it to that.

**Comment by 1337Smithy** [comment]
Fix: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/c895450ecaf06493cdeebb8485efcb09d6471156

Needs testing

**Comment by ChannelDaniila** [comment]
Fixed.
