### ISSUE TITLE
e1l1 - mission does not complete

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#37]
e1l1 does not complete.
Convoy at the end is not visible.

"no thread to ran thread" also occurred in the logs

This bug does not always happen.

![e1l1_mission_end_convoy_not_visible_and_mission_does_not_end](https://user-images.githubusercontent.com/13020991/101987956-272e3500-3c97-11eb-966e-33c151ccacc0.jpg)

**Comment by Chrissstrahl** [comment]
It has been suggested that not all tasks have been completed and the mission does not continue because of that.
I don't think this is the case, but it should also be investigated.

**Comment by ChannelDaniila** [comment]
IMPORTANT INFORMATION! IF YOU SKIPPED "Locate and Seize Enemy Artillery" TASK, CONVOY WILL BE INVISIBLE! ![изображение](https://user-images.githubusercontent.com/75738095/102018418-d17c8a00-3d75-11eb-959b-5ab9138e6020.png)

**Comment by ChannelDaniila** [comment]
If not, convoy is being normal and scripts is working.

**Comment by Chrissstrahl** [comment]
okay, great, I will make it so that you can't enter the outpost/bunker if that objective is not completed, so players do not have to walk so far to fix that.

**Comment by Chrissstrahl** [comment]
Use flashing red text to tell players that they can only enter the base if the artillery objective is complete

**Comment by ChannelDaniila** [comment]
What flashing red text?

**Comment by Chrissstrahl** [comment]
While you are at it, can you check if you can add some debug infos so we can see if there are any threads that get spawned over and over again unssearly ? Just a quick check, nothing fancy, we have debug in place from the coop mod thread stuff and should be seeing some results from that if you keep the logfile while testing it.

**Comment by 1337Smithy** [comment]
I've added some debug to ai.scr.

I've added change to bunker start so player can't enter until artillery are seized. But bug persists if you don't pick up the documents at bunker exit. I will also block player at bunker exit too. 

Fix incoming...

**Comment by 1337Smithy** [comment]
Should be fixed. Players are blocked and final door now locks. 

https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/ec7402be59a32da8b20c62ae17e811c9dc5ba706

**Comment by Chrissstrahl** [comment]
It is closed but got label needs testing, I am confused, reopening it until it was tested.

**Comment by ChannelDaniila** [comment]
I tested this fix and this works fine.
