### ISSUE TITLE
Unknown animation 'unarmed_aim' in models/human/german_waffenss_shutze.tik

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#49]
self setactionanim (self.weapongroup + "_aim") -60 60 (anim/attack.scr, 1176)
			self ^
^~^~^ Script Error: unknown animation 'unarmed_aim' in 'models/human/german_waffenss_shutze.tik'
^~^~^ Attack medium range default case for unarmed weapon group - fix attack.scr
m4l2

**Comment by 1337Smithy** [comment]
Fix: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/08c4b29b548d53a7e46cd3420efcde1b9707b370

**Comment by 1337Smithy** [comment]
Testing already done.
