### ISSUE TITLE
snd_pickup needs an alias in ubersound.scr or uberdialog.scr - m4l3

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#50]
ERROR: Entity::Sound: snd_pickup needs an alias in ubersound.scr or uberdialog.scr - Please fix.
m4l3

**Comment by Chrissstrahl** [comment]
This is odd, it is already listed:
aliascache snd_pickup sound/weapons/foley/Pickup_01.wav soundparms 1.3 0.2 0.8 0.2 160 1000 item loaded maps "m1 m2 m3 m4 m5 m6 train"

**Comment by vitorsantos98** [comment]
Try doing this in a script to fix:

```
local.master = spawn ScriptMaster
local.master aliascache snd_pickup sound/weapons/foley/Pickup_01.wav soundparms 1.3 0.2 0.8 0.2 160 1000 item loaded maps "moh train"
```

**Comment by 1337Smithy** [comment]
What did you pick up to get this message? More info needed so I can test it :).

**Comment by Chrissstrahl** [comment]
No clue

**Comment by 1337Smithy** [comment]
Seems this message that pops up at level spawn in lots of maps, don't think it warrants an issue on here as I'm not convinced it even is one. We can always re-open if we deem it is.
