### ISSUE TITLE
Tank fire of player thank does not do good radius damage

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#53]
The radius damage of the player tank projectiles should originate a few units above ground to prevent the terrain from blocking the radiusdamage.
You can shoot right next to a ai in the ground and if there is some sort of terrain or hole or something it will completely block the damage to the ai that is standing like half a meter away from it, something that would never happen in reality.

**Comment by 1337Smithy** [comment]
Common issue with all projectiles in MOHAA. Will require a projectile handler to improve.
