### ISSUE TITLE
e1l1 - parade script error

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#54]
Initializing parade script
			if ($paradetrigger[local.i].target.target == NIL) //chrissstrahl - it probably is right (global/parade.scr, 103)
			if ($paradetrigger[local.i].target^

^~^~^ Script Error: There are 0 entities with targetname 'bunkerapproachorigin'. You are using a command that requires exactly one.

parade script origin has no target
Initializing parade abort 1
				$paradedeletetrigger[local.i] setthread DeleteParadeTrigger (global/parade.scr, 145)
				$paradedeletetrigger[local.i] ^

^~^~^ Script Error: Failed execution of command 'setthread' for class 'PathNode' Targetname 'paradedeletetrigger'

**Comment by Chrissstrahl** [comment]
I could not fix this, this could be a multiplayer problem or not.
I didn't really bother with it, but it would be nice to not have that error message in the logs.

**Comment by vitorsantos98** [comment]
This check is wrong, should be like this:
```f ($paradetrigger[local.i].target == NIL)```

**Comment by 1337Smithy** [comment]
I assume it's trying to find the target's targetm I.e. 2 nodes away, so not necessarily wrong. It probably should include a check on the first target though.

**Comment by 1337Smithy** [comment]
`$paradetrigger[local.i].target.target`  is correct. 

the check beforehand required was:

`if($($paradetrigger[local.i].target) == NULL){ continue }`

To check the entity exists. Also included a classname check for dev errors on map.

Should be fixed: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/32409c598c7412175baff0d2a6321f098d760698
