### ISSUE TITLE
e1l1 + e1l2 - Level::AllocEdict: no free edicts

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#55]
The following error is happening on a dedicated server started with Breakthrough_Server_Setup.exe
This is always happening on e1l1/e1l2 ONLY if the following settings are enabled:
seta coop_dev 1
seta coop_diag 1

Note that if diagnose modus is activated the timescale is changed for faster testing.

-------------------- Spawning Entities Done ------------------ 414 ms
^~^~^ Add the following line to the *_precache.scr map script:
cache models/items/binoculars.tik
********************
ERROR: Level::AllocEdict: no free edicts
********************
----- Server Shutdown -----
==== ShutdownGame ====

**Comment by 1337Smithy** [comment]
Can't seem to replicate it. Unlikely to fix until I can.
