### ISSUE TITLE
m1l1 - Intro truck sequence is very jittery for clients

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#59]
You know the issue, maybe you can implement your new solution here too :)

**Comment by 1337Smithy** [comment]
It's an enhancement, but I've only recently implemented this code so it's fresh in my mind, and it's the first mission which we want to perform well so players have more confidence in the mod, so I'll work on it.

**Comment by 1337Smithy** [comment]
Fix: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/760616214fde969565b9a8caead87df2614a13fe

Intro scene will need testing. E.g. go to spec, go back to allies, and test with multiple players.

**Comment by ChannelDaniila** [comment]
Tested, fix is working.

**Comment by 1337Smithy** [comment]
Testing with multiple players. Still jittery and got stuck in truck after intro scene. Needs fixing.

**Comment by 1337Smithy** [comment]
Fixed
