### ISSUE TITLE
e1l3 - Klaus not talking and cutscene not working

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#63]
Klaus just staying and doing nothing.

**Comment by 1337Smithy** [comment]
Which cutscene? The first one where you meet Klaus?

**Comment by 1337Smithy** [comment]
Can't replicate this. Unlikely to fix until I can. More details of the scenario that managed to break it is required.

**Comment by Chrissstrahl** [comment]
A video recording could help in replicating this

**Comment by ChannelDaniila** [comment]
Strange, but this issue is fixed automatically) I'm seriously. Now Klaus is finally talking. I'm closing this issue.

**Comment by Chrissstrahl** [comment]
This can be if the server was having issues after several maps.
Make sure to reboot server, quit game and reconnect to verify issues that seam random.

**Comment by 1337Smithy** [comment]
It could have been player 0 issue. So yep, best to close it down now we have other fixes in place that could solve this problem.
