### ISSUE TITLE
m6l3a - Invidible blockade inside Train at map start

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#68]
Maybe removing the invisible blockade, that restricts players to a certain area inside the train.
I am not sure how much work this will be or if it is a easy fix, so I am not giving this any priority.
Players are in this area for a short amount of time.

**Comment by 1337Smithy** [comment]
I suspect this blockade is here to stop players messing with the friendlies as they do their anims and what not. E.g. they crouch and then stand and so on. I think for now we keep it in. As you say, they are in there for like 30 seconds and are then thrust upon the world of snipers thusly. Closed.
