### ISSUE TITLE
m6l3a - Mission is stuck

### ISSUE THREAD

**Issue by Chrissstrahl** [Chrissstrahl/hzm-mohaa-coop-mod#69]
Storming Fort Schmerzen (Train platform) - there is no sound or dialog happening at the start of the map.
Players are spawned inside the train and can shoot their NPC Teammates.
There seams to be no way to get the mission unstuck.

Also we should look into removing the invisible blockade, see: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/issues/68

**Comment by 1337Smithy** [comment]
Should be fixed.
