### ISSUE TITLE
m6l1c - Stealth not working at beginning

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#70]
When you spawning, MG-42 automaticly shooting you.

**Comment by ChannelDaniila** [comment]
![Image](https://user-images.githubusercontent.com/75738095/103432475-1282f400-4be8-11eb-822a-124eedf2a78c.png)

**Comment by 1337Smithy** [comment]
Fixed: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/344f2dd2d4f49708595625958d0e6067ae53cba2

**Comment by ChannelDaniila** [comment]
Tested, fix is working.
