### ISSUE TITLE
m6l3e - Player can only move

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#73]
At this level player can only move, he don't have any weapon and he can't move camera.

**Comment by ChannelDaniila** [comment]
![Image](https://user-images.githubusercontent.com/75738095/103439920-e0a27980-4c49-11eb-815e-d469ba15aca7.png)

**Comment by 1337Smithy** [comment]
Had the ending been triggered? It may the ending scene that did it

**Comment by ChannelDaniila** [comment]
No. When i spawned, i can't do anything, only move. That player too.

**Comment by ChannelDaniila** [comment]
Strange, i'm playing now and everything is normal now on this map. Idk what was it...

**Comment by 1337Smithy** [comment]
I can't seem to replicate this issue.
