### ISSUE TITLE
m6l2a - Snipers not shooting

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#74]
Snipers only aim, but do not shoot.

**Comment by ChannelDaniila** [comment]
![Image](https://user-images.githubusercontent.com/75738095/103440217-7b9c5300-4c4c-11eb-8d23-b4e06542a37a.png)

**Comment by 1337Smithy** [comment]
Fixed: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/e2b0c172819c6701ac74982bfb84bc166f8ba374

**Comment by ChannelDaniila** [comment]
Tested, fix is working.
