### ISSUE TITLE
e1l2 - Jeep intro scene is jittery

### ISSUE THREAD

**Issue by 1337Smithy** [Chrissstrahl/hzm-mohaa-coop-mod#76]

**Comment by 1337Smithy** [comment]
https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/868d95855c29a570e365f59f8479635ebaf4c8c0

Needs testing with multiple players on server.

**Comment by ChannelDaniila** [comment]
Tested. Fix is working.
