### ISSUE TITLE
e1l4 - Invisible gates

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#93]
![Image](https://user-images.githubusercontent.com/75738095/103468744-2011b880-4d65-11eb-84d7-8d54b5e4cd34.png)

**Comment by Chrissstrahl** [comment]
Invisible gates is a texture(shader) issue, we already discussed this like 3 months ago.
There is nothing that we can do right now short of editing the mapfiles.
