### ISSUE TITLE
m3l1a - Players can stuck in LCVC boat

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#94]
For example: 
![Image](https://user-images.githubusercontent.com/75738095/103483253-9dcdd680-4dee-11eb-958e-29355fc7d0ec.png)
Players stuck in boat and this stopping cutscene.

**Comment by ChannelDaniila** [comment]
Not very good screenshot, but i hope you understand me without that.

**Comment by 1337Smithy** [comment]
Fixed.
