### ISSUE TITLE
m5l3 - NPCs don't want to explode the bridge

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#96]
![Image](https://user-images.githubusercontent.com/75738095/103587049-0f8d4980-4eef-11eb-870c-902e9cf32a7d.png)

**Comment by 1337Smithy** [comment]
Fixed: https://github.com/Chrissstrahl/hzm-mohaa-coop-mod/commit/c9a8156d0f96f8b70f10f30b0c04d5ac1aabb778
